server:
  port: 1008

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: admin-contact-service
          uri: lb://admin-contact-service
          predicates:
            - Path=/contacts/**


        - id: train-order-service
          uri: lb://train-order-service
          predicates:
            - Path=/booking/**


        - id: train-service
          uri: lb://train-service
          predicates:
            - Path=/trains/** , /search/**